### ISSUE TITLE
透明度を扱わないフラグの付与

### ISSUE THREAD

**Issue by nazonoSAUNA** [sigma-axis/aviutl_rot_center#1]
https://x.com/nazono22/status/1767106413174882666

https://github.com/nazonoSAUNA/patch.aul/blob/r43_59/patch/patch_fast_yc_filter_effect.hpp#L262

Filter::Flagの0x40はもともと一部の入力フィルタと出力フィルタにしか設定されていませんでしたが、Patchにてエフェクトでも対応するようになります。

おそらく透明度を扱わない部類のフィルタのはずなので0x40を付与するだけで良さそうです

**Comment by sigma-axis** [comment]
[v1.01](https://github.com/sigma-axis/aviutl_rot_center/releases/tag/v1.01) で対応しました．きちんと `efpip->no_alpha` が立っていることも確認できています（四角形と背景オブジェクトで確認）．
